// Generated by https://quicktype.io

export interface MangadexCover {
  result:   string;
  response: string;
  data:     Datum[];
  limit:    number;
  offset:   number;
  total:    number;
}

export interface Datum {
  id:            string;
  type:          DatumType;
  attributes:    Attributes;
  relationships: Relationship[];
}

export interface Attributes {
  description: string;
  volume:      string;
  fileName:    string;
  locale:      Locale;
  createdAt:   string;
  updatedAt:   string;
  version:     number;
}

export enum Locale {
  Ja = "ja",
}

export interface Relationship {
  id:   string;
  type: RelationshipType;
}

export enum RelationshipType {
  Manga = "manga",
  User = "user",
}

export enum DatumType {
  CoverArt = "cover_art",
}
