// Generated by https://quicktype.io

export interface MangadexManga {
  result:   string;
  response: string;
  data:     Datum[];
  limit:    number;
  offset:   number;
  total:    number;
}

export interface Datum {
  id:            string;
  type:          string;
  attributes:    DatumAttributes;
  relationships: Relationship[];
}

export interface DatumAttributes {
  title:                          Title;
  altTitles:                      { [key: string]: string }[];
  description:                    PurpleDescription;
  isLocked:                       boolean;
  links:                          { [key: string]: string };
  originalLanguage:               string;
  lastVolume:                     string;
  lastChapter:                    string;
  publicationDemographic:         string;
  status:                         string;
  year:                           number;
  contentRating:                  string;
  tags:                           Tag[];
  state:                          string;
  chapterNumbersResetOnNewVolume: boolean;
  createdAt:                      string;
  updatedAt:                      string;
  version:                        number;
  availableTranslatedLanguages:   Array<null | string>;
  latestUploadedChapter:          string;
}

export interface PurpleDescription {
  en:      string;
  pl:      string;
  "pt-br": string;
}

export interface Tag {
  id:            string;
  type:          string;
  attributes:    TagAttributes;
  relationships: any[];
}

export interface TagAttributes {
  name:        Title;
  description: FluffyDescription;
  group:       string;
  version:     number;
}

export interface FluffyDescription {
}

export interface Title {
  en: string;
}

export interface Relationship {
  id:          string;
  type:        string;
  attributes?: RelationshipAttributes;
  related?:    string;
}

export interface RelationshipAttributes {
  description: string;
  volume:      string;
  fileName:    string;
  locale:      string;
  createdAt:   string;
  updatedAt:   string;
  version:     number;
}
